name: CI Builds

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@main
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install make g++ libssl-dev libpcsclite-dev pcscd pkgconf libcurl4-openssl-dev python3
        ./thirdparty/tsduck/scripts/install-prerequisites.sh

    - name: Generate TSDuck headers
      run: |
        mkdir -p thirdparty/tsduck/bin/include
        python3 thirdparty/tsduck/scripts/build-tsduck-header.py tscore thirdparty/tsduck/bin/include/tscore.h
        python3 thirdparty/tsduck/scripts/build-tsduck-header.py tsduck thirdparty/tsduck/bin/include/tsduck.h

    - name: Build TSDuck
      run: |
        cd ./thirdparty/tsduck
        make STATIC=1 NODOXYGEN=1 NOTEST=1 -j$(nproc)

    - name: Build dantto4k
      run: make STATIC_TSDUCK=1 -j$(nproc)

    - name: Package
      run: |
        PACKAGE="dantto4k-linux"
        mkdir -p "$PACKAGE"

        cp build/dantto4k "$PACKAGE/"
        cp -r ini/. "$PACKAGE/"

        echo "PACKAGE_DIR=$PACKAGE" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: dantto4k-linux
        path: ${{ env.PACKAGE_DIR }}
        if-no-files-found: error
        
  windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@main
        with:
          submodules: recursive
      
      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.x"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@main
        with:
          vs-version: "[17.10,"

      - name: Generate TSDuck headers
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $binInclude = "thirdparty\tsduck\bin\include"
          New-Item -ItemType Directory -Force $binInclude | Out-Null
          python "thirdparty\tsduck\scripts\build-tsduck-header.py" tscore "$binInclude\tscore.h"
          python "thirdparty\tsduck\scripts\build-tsduck-header.py" tsduck "$binInclude\tsduck.h"

      - name: Build TSDuck
        env:
          _CL_: /D_USE_STD_VECTOR_ALGORITHMS=0 /MT /WX-
        run: msbuild thirdparty\tsduck\scripts\msvc\tsduck.sln /m /t:tsducklib /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

      - name: Build dantto4k
        run: msbuild msvc\dantto4k.sln /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

      - name: Package
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $package = "dantto4k-win64"
          $stage = Join-Path $env:RUNNER_TEMP $package
          New-Item -ItemType Directory -Force -Path $stage | Out-Null

          Copy-Item msvc\x64\Release\dantto4k.exe $stage
          Copy-Item msvc\x64\Release\BonDriver_dantto4k.dll $stage
          Copy-Item ini\BonDriver_dantto4k.ini $stage -Recurse

          "PACKAGE_DIR=$stage" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: dantto4k-windows
          path: ${{ env.PACKAGE_DIR }}
          if-no-files-found: error